apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: 
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: 494108812211.dkr.ecr.eu-west-2.amazonaws.com/project-frontend:1.0
        ports: 
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
