apiVersion: apps/v1
kind: Deployment
metadata: 
  name: love-games-backend
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: love-games-backend
  template:
    metadata:
      labels:
        app: love-games-backend
    spec:
      containers:
      - name: love-games-backend
        image: 494108812211.dkr.ecr.eu-west-2.amazonaws.com/lovegames-project-backend:1.0
        ports: 
        - containerPort: 8080
      imagePullSecrets:
        - name: regcredlove
