apiVersion: apps/v1
kind: Deployment
metadata:
  name: love-games-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: love-games-frontend
  template:
    metadata:
      labels:
        app: love-games-frontend
    spec:
      containers:
        - name: love-games-frontend
          image: 494108812211.dkr.ecr.eu-west-2.amazonaws.com/lovegames-project-frontend:1.1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: testecr
